#!/usr/bin/env bash
# Fail when dist/ recovery artifacts do not match the current checkout.
#
# WHY THIS EXISTS
#
# dist/airouter-unpushed.bundle and dist/airouter-unpushed.patch are generated,
# gitignored artifacts. They are the only record that the local-only commits
# exist outside this working tree. They are regenerated by hand, and a
# hand-maintained artifact goes stale silently: it still exists, it is still
# non-empty, and it still verifies -- it just describes an older commit than the
# one checked out.
#
# That is the worst failure shape available here. A missing bundle is obvious.
# A stale bundle looks authoritative, and a handoff built from it would
# silently omit every commit made since. dist/README.md tells the next session
# to check the bundle tip against HEAD, which is right, and it was the right
# instruction only because a session remembered to run it.
#
# This makes the check a gate instead of a note. It compares three things:
#
#   1. the bundle's recorded tip against HEAD;
#   2. the patch's last commit against HEAD;
#   3. the unpushed set the artifacts claim to cover against the unpushed set
#      that actually exists.
#
# Checking only the tip would pass for a bundle that carried the right commit
# and dropped others, so the third check counts and compares the whole set.
#
# WHY NOT JUST REGENERATE
#
# Because regenerating inside a check hides the problem instead of reporting it.
# A check that silently rewrites the artifacts reports success for work it never
# verified, and if regeneration itself is what broke, that is invisible. This
# reports, and tells the reader the one command to run.
#
# WHAT IT DELIBERATELY ALLOWS
#
# A checkout with nothing unpushed is clean, not stale: there is nothing to
# carry, so no artifacts are required. Likewise a checkout whose artifacts are
# absent is reported as absent rather than assumed fresh -- the artifacts are
# local state, and a machine that cannot see them cannot vouch for them.
#
# Usage: scripts/dist-freshness-check.sh [--verbose]
# Exit 0 = artifacts match HEAD, or there is nothing to carry.
# Exit 1 = artifacts are missing or stale.
# Exit 2 = the check could not run (not a repository, no upstream ref).
set -uo pipefail

VERBOSE=0
[ "${1:-}" = "--verbose" ] && VERBOSE=1

cd "$(dirname "$0")/.." || exit 2

UPSTREAM="${UPSTREAM:-origin/master}"
BUNDLE="dist/airouter-unpushed.bundle"
PATCH="dist/airouter-unpushed.patch"
VERBOSE_PREFIX="dist-freshness-check:"

say() { [ "$VERBOSE" -eq 1 ] && printf '  %s\n' "$1"; return 0; }

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "${VERBOSE_PREFIX} not a git repository" >&2
  exit 2
fi

if ! git rev-parse --verify --quiet "$UPSTREAM" >/dev/null 2>&1; then
  echo "${VERBOSE_PREFIX} $UPSTREAM does not exist; cannot determine what is unpushed" >&2
  echo "  fetch first, or set UPSTREAM=<ref>. Without it this check cannot run," >&2
  echo "  and a check that cannot run must not report success." >&2
  exit 2
fi

HEAD_SHA=$(git rev-parse HEAD)
count=$(git rev-list --count "$UPSTREAM"..HEAD)

# Nothing unpushed: no artifacts are required, and their absence is correct.
if [ "$count" -eq 0 ]; then
  say "ok: nothing unpushed ($UPSTREAM is level with HEAD); no artifacts required"
  echo "${VERBOSE_PREFIX} nothing to carry ($UPSTREAM..HEAD is empty)"
  exit 0
fi

problems=""

# 1. Bundle tip. The bundle stores the tip as a named ref; read it back rather
#    than trusting the filename.
if [ ! -r "$BUNDLE" ]; then
  problems="${problems}${problems:+; }$BUNDLE is missing while $count commit(s) are unpushed"
else
  tip=$(git bundle list-heads "$BUNDLE" 2>/dev/null | awk 'NR==1{print $1}')
  if [ -z "$tip" ]; then
    problems="${problems}${problems:+; }$BUNDLE has no readable tip"
  elif [ "$tip" != "$HEAD_SHA" ]; then
    short=$(git rev-parse --short "$tip" 2>/dev/null || printf '%s' "${tip:0:7}")
    problems="${problems}${problems:+; }$BUNDLE tip is $short, but HEAD is $(git rev-parse --short HEAD)"
  else
    say "ok: bundle tip matches HEAD ($(git rev-parse --short HEAD))"
  fi
fi

# 2. Patch tail. The last "From <sha>" line names the final commit it carries.
if [ ! -r "$PATCH" ]; then
  problems="${problems}${problems:+; }$PATCH is missing while $count commit(s) are unpushed"
else
  # The LAST "From <sha>" header names the final commit the patch carries.
  tail_sha=$(grep '^From [0-9a-f]\{40\} ' "$PATCH" | tail -1 | awk '{print $2}')
  if [ -z "$tail_sha" ]; then
    problems="${problems}${problems:+; }$PATCH has no readable commit headers"
  elif [ "$tail_sha" != "$HEAD_SHA" ]; then
    problems="${problems}${problems:+; }$PATCH ends at $(git rev-parse --short "$tail_sha" 2>/dev/null || printf '%s' "${tail_sha:0:7}"), but HEAD is $(git rev-parse --short HEAD)"
  else
    say "ok: patch ends at HEAD ($(git rev-parse --short HEAD))"
  fi
  patch_count=$(grep -c '^From [0-9a-f]\{40\} ' "$PATCH")
  if [ "$patch_count" != "$count" ]; then
    problems="${problems}${problems:+; }$PATCH carries $patch_count commit(s), but $count are unpushed"
  else
    say "ok: patch carries all $count unpushed commit(s)"
  fi
fi

if [ -n "$problems" ]; then
  echo "${VERBOSE_PREFIX} FAILED — the recovery artifacts are stale:" >&2
  IFS=';' read -ra parts <<< "$problems"
  for p in "${parts[@]}"; do
    [ -n "$p" ] && echo "  - $p" >&2
  done
  echo "" >&2
  echo "  The bundle and patch are the only record of the $count unpushed" >&2
  echo "  commit(s) once this checkout is gone, and a stale one silently omits" >&2
  echo "  whatever was committed since. Regenerate with:" >&2
  echo "    ./scripts/export-unpushed.sh" >&2
  exit 1
fi

echo "${VERBOSE_PREFIX} artifacts match HEAD; $count unpushed commit(s) covered"
exit 0
